/*
 * Zigbee DMX Bridge - DMX Output Implementation
 *
 * Implements DMX512 output using ESP32 UART1 hardware directly.
 * The UART is configured for 250000 baud, 8N2.
 * The BREAK signal is generated by temporarily switching to a lower baud rate.
 *
 * RS-485 transceiver enable pin is driven HIGH during transmission.
 */

#include "dmx_output.h"
#include "driver/uart.h"
#include "driver/gpio.h"

DmxOutput dmxOutput;

// Use UART1 for DMX
static const uart_port_t DMX_UART = UART_NUM_1;

void DmxOutput::begin() {
  if (initialized) return;

  // Configure RS-485 enable pin
  gpio_set_direction(static_cast<gpio_num_t>(DMX_EN_PIN), GPIO_MODE_OUTPUT);
  gpio_set_level(static_cast<gpio_num_t>(DMX_EN_PIN), 1);  // Enable TX

  // Configure UART for DMX: 250000 baud, 8N2
  uart_config_t uart_config = {};
  uart_config.baud_rate = 250000;
  uart_config.data_bits = UART_DATA_8_BITS;
  uart_config.parity    = UART_PARITY_DISABLE;
  uart_config.stop_bits = UART_STOP_BITS_2;
  uart_config.flow_ctrl = UART_HW_FLOWCTRL_DISABLE;
  uart_config.source_clk = UART_SCLK_DEFAULT;

  ESP_ERROR_CHECK(uart_param_config(DMX_UART, &uart_config));
  ESP_ERROR_CHECK(uart_set_pin(DMX_UART, DMX_TX_PIN, DMX_RX_PIN, UART_PIN_NO_CHANGE, UART_PIN_NO_CHANGE));

  // Install UART driver (TX buffer of 1024 bytes, RX buffer must be >= SOC_UART_FIFO_LEN)
  ESP_ERROR_CHECK(uart_driver_install(DMX_UART, 256, 1024, 0, NULL, 0));

  memset(dmxData, 0, sizeof(dmxData));
  initialized = true;

  ESP_LOGI("DMX", "DMX output initialized on TX=%d, EN=%d", DMX_TX_PIN, DMX_EN_PIN);
}

void DmxOutput::sendBreak() {
  // Generate BREAK by sending a zero byte at a much lower baud rate
  // At 90909 baud, one byte frame (start + 8 data + stop) = ~110us
  // which satisfies the >=88us BREAK requirement.
  uart_wait_tx_done(DMX_UART, pdMS_TO_TICKS(100));

  // Temporarily set low baud rate for BREAK
  uart_set_baudrate(DMX_UART, 90909);
  uint8_t breakByte = 0x00;
  uart_write_bytes(DMX_UART, &breakByte, 1);
  uart_wait_tx_done(DMX_UART, pdMS_TO_TICKS(100));

  // Restore DMX baud rate (Mark After Break is generated by the idle line
  // between the BREAK byte and the first data byte)
  uart_set_baudrate(DMX_UART, 250000);
}

void DmxOutput::sendData() {
  // Send start code + channel data
  // dmxData[0] = 0x00 (start code for DMX)
  // dmxData[1..512] = channel values
  uart_write_bytes(DMX_UART, dmxData, sizeof(dmxData));
}

void DmxOutput::update(const LightConfig* lights, const LightState* states, uint8_t count) {
  if (!initialized) return;

  // Clear data channels (keep start code = 0)
  memset(&dmxData[1], 0, 512);

  for (uint8_t i = 0; i < count; i++) {
    const LightConfig& cfg = lights[i];
    const LightState& state = states[i];

    if (!cfg.active) continue;
    if (cfg.dmxStartAddr < 1 || cfg.dmxStartAddr > 512) continue;

    uint16_t base = cfg.dmxStartAddr;

    // Apply brightness scaling (Zigbee brightness is 0-254)
    float briScale = state.powerOn ? (static_cast<float>(state.brightness) / 254.0f) : 0.0f;

    // Map color channels to DMX addresses
    uint16_t rAddr = base + cfg.channelMap.red;
    uint16_t gAddr = base + cfg.channelMap.green;
    uint16_t bAddr = base + cfg.channelMap.blue;

    if (rAddr >= 1 && rAddr <= 512) dmxData[rAddr] = static_cast<uint8_t>(state.red * briScale);
    if (gAddr >= 1 && gAddr <= 512) dmxData[gAddr] = static_cast<uint8_t>(state.green * briScale);
    if (bAddr >= 1 && bAddr <= 512) dmxData[bAddr] = static_cast<uint8_t>(state.blue * briScale);

    if (cfg.type == LIGHT_TYPE_RGBW) {
      uint16_t wAddr = base + cfg.channelMap.white;
      if (wAddr >= 1 && wAddr <= 512) dmxData[wAddr] = static_cast<uint8_t>(state.white * briScale);
    }
  }

  // Send DMX frame: BREAK + data
  sendBreak();
  sendData();
}

void DmxOutput::stop() {
  if (!initialized) return;
  uart_driver_delete(DMX_UART);
  gpio_set_level(static_cast<gpio_num_t>(DMX_EN_PIN), 0);
  initialized = false;
}
